# Generated by Django 5.2.4 on 2025-10-25 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
