# Generated by Django 5.2.4 on 2025-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_post_date_posted_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pics',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
    ]
