# Generated by Django 5.2.4 on 2025-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
