# Generated by Django 5.2.4 on 2025-09-07 21:41

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
